  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Set up Ruby
    # It's best practice to use a maintained version tag (like v1)
    # to automatically get bug fixes and new Ruby versions.
    # Note: Ruby 2.6.1 is an older, end-of-life version and will
    # not receive security patches. Consider upgrading to a
    # supported version if possible.
    uses: ruby/setup-ruby@v1
    with:
      ruby-version: 2.6.1

  - name: Publish to GPR (GitHub Packages)
    run: |
      mkdir -p $HOME/.gem
      touch $HOME/.gem/credentials
      chmod 0600 $HOME/.gem/credentials
      # Configure credentials for GitHub Packages Registry
      printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
      
      # Build the gem and push to GitHub Packages
      gem build *.gemspec
      gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
    env:
      GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
      OWNER: ${{ github.repository_owner }}
      
  - name: Publish to RubyGems
    run: |
      mkdir -p $HOME/.gem
      touch $HOME/.gem/credentials
      chmod 0600 $HOME/.gem/credentials
      # Configure credentials for RubyGems.org
      printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
      
      # Build the gem and push to RubyGems.org
      gem build *.gemspec
      gem push *.gem
    env:
      GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
