name: Ruby Gem CI/CD

on:
  push:
    tags:
      - "v*" # Trigger only when you push a version tag like v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.1  # Consider upgrading to >= 3.0

      - name: Publish to GitHub Packages
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          # Configure credentials for GitHub Packages Registry
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          
          # Build the gem and push to GitHub Packages
          gem build *.gemspec
          gem push --key github --host "https://rubygems.pkg.github.com/${OWNER}" *.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{ secrets.GITHUB_TOKEN }}"
